### PR TITLE
Dev: Jenkins Deployment Docker

### PR DESCRIPTION
**Pull request by TURP1**

### CODE REVIEW

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Review by irinrudko — APPROVED** [review]

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Comment by TURP1** [comment]
run build production

**Review by Viarcinski — APPROVED** [review]

**Review by ilich01 — APPROVED** [review]

**Comment by TURP1** [comment]
run build production

**Pull request merged**
